// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "xraytool/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// Engine is an autogenerated mock type for the Engine type
type Engine struct {
	mock.Mock
}

// AddUser provides a mock function with given fields: ctx, user
func (_m *Engine) AddUser(ctx context.Context, user domain.VPNUserConfig) error {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for AddUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.VPNUserConfig) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AddUsersBulk provides a mock function with given fields: ctx, users
func (_m *Engine) AddUsersBulk(ctx context.Context, users []domain.VPNUserConfig) error {
	ret := _m.Called(ctx, users)

	if len(ret) == 0 {
		panic("no return value specified for AddUsersBulk")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []domain.VPNUserConfig) error); ok {
		r0 = rf(ctx, users)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BanUser provides a mock function with given fields: ctx, email
func (_m *Engine) BanUser(ctx context.Context, email string) error {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for BanUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ListUsers provides a mock function with given fields: ctx
func (_m *Engine) ListUsers(ctx context.Context) ([]domain.VPNUserConfig, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListUsers")
	}

	var r0 []domain.VPNUserConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.VPNUserConfig, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.VPNUserConfig); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.VPNUserConfig)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// QueryStats provides a mock function with given fields: ctx
func (_m *Engine) QueryStats(ctx context.Context) ([]domain.TrafficStat, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for QueryStats")
	}

	var r0 []domain.TrafficStat
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.TrafficStat, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.TrafficStat); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.TrafficStat)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemoveUser provides a mock function with given fields: ctx, email
func (_m *Engine) RemoveUser(ctx context.Context, email string) error {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for RemoveUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RemoveUsersBulk provides a mock function with given fields: ctx, emails
func (_m *Engine) RemoveUsersBulk(ctx context.Context, emails []string) error {
	ret := _m.Called(ctx, emails)

	if len(ret) == 0 {
		panic("no return value specified for RemoveUsersBulk")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) error); ok {
		r0 = rf(ctx, emails)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RestartLogger provides a mock function with given fields: ctx
func (_m *Engine) RestartLogger(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for RestartLogger")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetExpire provides a mock function with given fields: ctx, email, expire
func (_m *Engine) SetExpire(ctx context.Context, email string, expire string) error {
	ret := _m.Called(ctx, email, expire)

	if len(ret) == 0 {
		panic("no return value specified for SetExpire")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, email, expire)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetLimit provides a mock function with given fields: ctx, email, limit
func (_m *Engine) SetLimit(ctx context.Context, email string, limit float64) error {
	ret := _m.Called(ctx, email, limit)

	if len(ret) == 0 {
		panic("no return value specified for SetLimit")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, float64) error); ok {
		r0 = rf(ctx, email, limit)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SyncUsers provides a mock function with given fields: ctx, dbUsers, removeOrphans
func (_m *Engine) SyncUsers(ctx context.Context, dbUsers []domain.VPNUserConfig, removeOrphans bool) (*domain.EngineSyncResult, error) {
	ret := _m.Called(ctx, dbUsers, removeOrphans)

	if len(ret) == 0 {
		panic("no return value specified for SyncUsers")
	}

	var r0 *domain.EngineSyncResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []domain.VPNUserConfig, bool) (*domain.EngineSyncResult, error)); ok {
		return rf(ctx, dbUsers, removeOrphans)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []domain.VPNUserConfig, bool) *domain.EngineSyncResult); ok {
		r0 = rf(ctx, dbUsers, removeOrphans)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.EngineSyncResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []domain.VPNUserConfig, bool) error); ok {
		r1 = rf(ctx, dbUsers, removeOrphans)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UnbanUser provides a mock function with given fields: ctx, email
func (_m *Engine) UnbanUser(ctx context.Context, email string) error {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for UnbanUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RebuildInbound provides a mock function with given fields: ctx, tag
func (_m *Engine) RebuildInbound(ctx context.Context, tag string) error {
	ret := _m.Called(ctx, tag)

	if len(ret) == 0 {
		panic("no return value specified for RebuildInbound")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, tag)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewEngine creates a new instance of Engine. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEngine(t interface {
	mock.TestingT
	Cleanup(func())
}) *Engine {
	mock := &Engine{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
