// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "xraytool/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// Registry is an autogenerated mock type for the Registry type
type Registry struct {
	mock.Mock
}

// AntifraudBans provides a mock function with no fields
func (_m *Registry) AntifraudBans() domain.AntifraudBanRepository {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for AntifraudBans")
	}

	var r0 domain.AntifraudBanRepository
	if rf, ok := ret.Get(0).(func() domain.AntifraudBanRepository); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.AntifraudBanRepository)
		}
	}

	return r0
}

// Devices provides a mock function with no fields
func (_m *Registry) Devices() domain.DeviceRepository {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Devices")
	}

	var r0 domain.DeviceRepository
	if rf, ok := ret.Get(0).(func() domain.DeviceRepository); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.DeviceRepository)
		}
	}

	return r0
}

// Notifications provides a mock function with no fields
func (_m *Registry) Notifications() domain.SubscriptionNotificationRepository {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Notifications")
	}

	var r0 domain.SubscriptionNotificationRepository
	if rf, ok := ret.Get(0).(func() domain.SubscriptionNotificationRepository); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.SubscriptionNotificationRepository)
		}
	}

	return r0
}

// Payments provides a mock function with no fields
func (_m *Registry) Payments() domain.PaymentRepository {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Payments")
	}

	var r0 domain.PaymentRepository
	if rf, ok := ret.Get(0).(func() domain.PaymentRepository); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.PaymentRepository)
		}
	}

	return r0
}

// Plans provides a mock function with no fields
func (_m *Registry) Plans() domain.PlanRepository {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Plans")
	}

	var r0 domain.PlanRepository
	if rf, ok := ret.Get(0).(func() domain.PlanRepository); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.PlanRepository)
		}
	}

	return r0
}

// Promos provides a mock function with no fields
func (_m *Registry) Promos() domain.PromoRepository {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Promos")
	}

	var r0 domain.PromoRepository
	if rf, ok := ret.Get(0).(func() domain.PromoRepository); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.PromoRepository)
		}
	}

	return r0
}

// Subscriptions provides a mock function with no fields
func (_m *Registry) Subscriptions() domain.SubscriptionRepository {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Subscriptions")
	}

	var r0 domain.SubscriptionRepository
	if rf, ok := ret.Get(0).(func() domain.SubscriptionRepository); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.SubscriptionRepository)
		}
	}

	return r0
}

// Users provides a mock function with no fields
func (_m *Registry) Users() domain.UserRepository {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Users")
	}

	var r0 domain.UserRepository
	if rf, ok := ret.Get(0).(func() domain.UserRepository); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.UserRepository)
		}
	}

	return r0
}

// WithTx provides a mock function with given fields: ctx, fn
func (_m *Registry) WithTx(ctx context.Context, fn func(domain.Registry) error) error {
	ret := _m.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for WithTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(domain.Registry) error) error); ok {
		r0 = rf(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRegistry creates a new instance of Registry. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRegistry(t interface {
	mock.TestingT
	Cleanup(func())
}) *Registry {
	mock := &Registry{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
