services:
  backend:
    image: ghcr.io/zloyradetski/xraytool-go:latest
    container_name: xraytool_backend
    restart: always
    pid: "host"
    network_mode: "host"
    privileged: true
    command: ["--run-migrations"]
    volumes:
      # Проброс всей папки с настройками, базой и состояниями
      - ./data:/etc/xraytool
      # Прямой проброс конфига ядра Xray
      - /usr/local/etc/xray:/usr/local/etc/xray
      # Проброс /tmp для передачи файлов payloads Xray API на хост
      - /tmp:/tmp
      # Проброс папки для сохранения GeoIP/Geosite баз при апдейте
      - /usr/local/share/xray:/usr/local/share/xray
      # Проброс логов бэкенда
      - /var/log/xraytool:/var/log/xraytool
      # Проброс конфигов Hysteria (если используется)
      - /etc/hysteria:/etc/hysteria
      # Проброс оперативной памяти для антифрода
      - /dev/shm:/dev/shm
    # Uncomment and adjust if using Postgres instead of SQLite
    # environment:
    #   - XRAYTOOL_DB_DSN=postgres://user:pass@postgres:5432/xraytool
    # depends_on:
    #   - postgres

  watchtower:
    image: containrrr/watchtower
    container_name: xraytool_watchtower
    restart: always
    environment:
      - DOCKER_API_VERSION=1.44
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 300 --cleanup xraytool_backend